//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeesGame.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DefaultUIValues : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultUIValues defaultInstance = ((DefaultUIValues)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultUIValues())));
        
        public static DefaultUIValues Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beige")]
        public global::System.Drawing.Color ScrollbarBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ScrollbarBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color ScrollbarColor {
            get {
                return ((global::System.Drawing.Color)(this["ScrollbarColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menufont")]
        public string DefaultSpriteFont {
            get {
                return ((string)(this["DefaultSpriteFont"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("floorTile")]
        public string DefaultButtonBackground {
            get {
                return ((string)(this["DefaultButtonBackground"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keyOverlay")]
        public string DefaultButtonHoverBackground {
            get {
                return ((string)(this["DefaultButtonHoverBackground"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("horizontalEnd")]
        public string DefaultButtonSelectedBackground {
            get {
                return ((string)(this["DefaultButtonSelectedBackground"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wheat")]
        public global::System.Drawing.Color FileExplorerBackground {
            get {
                return ((global::System.Drawing.Color)(this["FileExplorerBackground"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smallfont")]
        public string DefaultEditorControlSpriteFont {
            get {
                return ((string)(this["DefaultEditorControlSpriteFont"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button_click")]
        public string ButtonSound {
            get {
                return ((string)(this["ButtonSound"]));
            }
        }
    }
}
