//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeesGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeesGame.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin game.
        /// </summary>
        internal static string begin {
            get {
                return ResourceManager.GetString("begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your
        ///color..
        /// </summary>
        internal static string color_picker_text {
            get {
                return ResourceManager.GetString("color_picker_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns.
        /// </summary>
        internal static string columns_edit_text {
            get {
                return ResourceManager.GetString("columns_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level files| *.lvl.
        /// </summary>
        internal static string file_dialog_filter_lvl {
            get {
                return ResourceManager.GetString("file_dialog_filter_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random maze.
        /// </summary>
        internal static string generate_random_maze {
            get {
                return ResourceManager.GetString("generate_random_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an index.
        /// </summary>
        internal static string index_picker_text {
            get {
                return ResourceManager.GetString("index_picker_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level complete.
        /// </summary>
        internal static string level_complete {
            get {
                return ResourceManager.GetString("level_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred parsing the level. Please check if the level file is valid.
        /// </summary>
        internal static string load_file_error_parse {
            get {
                return ResourceManager.GetString("load_file_error_parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to load the level: .
        /// </summary>
        internal static string load_file_error_with_comment {
            get {
                return ResourceManager.GetString("load_file_error_with_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Level.
        /// </summary>
        internal static string loadLevel {
            get {
                return ResourceManager.GetString("loadLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create level.
        /// </summary>
        internal static string map_editor {
            get {
                return ResourceManager.GetString("map_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newmaze {
            get {
                return ResourceManager.GetString("newmaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string rows_edit_text {
            get {
                return ResourceManager.GetString("rows_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to save file: .
        /// </summary>
        internal static string save_file_error_with_comment {
            get {
                return ResourceManager.GetString("save_file_error_with_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        internal static string victory {
            get {
                return ResourceManager.GetString("victory", resourceCulture);
            }
        }
    }
}
