//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeesGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeesGame.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin game.
        /// </summary>
        internal static string begin {
            get {
                return ResourceManager.GetString("begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your
        ///color.
        /// </summary>
        internal static string color_picker_text {
            get {
                return ResourceManager.GetString("color_picker_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns.
        /// </summary>
        internal static string columns_edit_text {
            get {
                return ResourceManager.GetString("columns_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string def {
            get {
                return ResourceManager.GetString("def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level files| *.lvl.
        /// </summary>
        internal static string file_dialog_filter_lvl {
            get {
                return ResourceManager.GetString("file_dialog_filter_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog of War.
        /// </summary>
        internal static string fow {
            get {
                return ResourceManager.GetString("fow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080p (Full HD).
        /// </summary>
        internal static string full_hd {
            get {
                return ResourceManager.GetString("full_hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random maze.
        /// </summary>
        internal static string generate_random_maze {
            get {
                return ResourceManager.GetString("generate_random_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720p (HD).
        /// </summary>
        internal static string hd {
            get {
                return ResourceManager.GetString("hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an index.
        /// </summary>
        internal static string index_picker_text {
            get {
                return ResourceManager.GetString("index_picker_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level complete.
        /// </summary>
        internal static string level_complete {
            get {
                return ResourceManager.GetString("level_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred parsing the level. Please check if the level file is valid.
        /// </summary>
        internal static string load_file_error_parse {
            get {
                return ResourceManager.GetString("load_file_error_parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to load the level: .
        /// </summary>
        internal static string load_file_error_with_comment {
            get {
                return ResourceManager.GetString("load_file_error_with_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Level.
        /// </summary>
        internal static string loadLevel {
            get {
                return ResourceManager.GetString("loadLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create level.
        /// </summary>
        internal static string map_editor {
            get {
                return ResourceManager.GetString("map_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easiest.
        /// </summary>
        internal static string mazegen_difficulty_easiest {
            get {
                return ResourceManager.GetString("mazegen_difficulty_easiest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string mazegen_difficulty_easy {
            get {
                return ResourceManager.GetString("mazegen_difficulty_easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Holes.
        /// </summary>
        internal static string mazegen_difficulty_hard {
            get {
                return ResourceManager.GetString("mazegen_difficulty_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Ladders.
        /// </summary>
        internal static string mazegen_difficulty_hardest {
            get {
                return ResourceManager.GetString("mazegen_difficulty_hardest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string mazegen_difficulty_medium {
            get {
                return ResourceManager.GetString("mazegen_difficulty_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newmaze {
            get {
                return ResourceManager.GetString("newmaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A*.
        /// </summary>
        internal static string playertype_astar {
            get {
                return ResourceManager.GetString("playertype_astar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Fill.
        /// </summary>
        internal static string playertype_floodfill {
            get {
                return ResourceManager.GetString("playertype_floodfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string playertype_human {
            get {
                return ResourceManager.GetString("playertype_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monte Carlo.
        /// </summary>
        internal static string playertype_monte_carlo {
            get {
                return ResourceManager.GetString("playertype_monte_carlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random walking player.
        /// </summary>
        internal static string playertype_random {
            get {
                return ResourceManager.GetString("playertype_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1440p (Quad HD).
        /// </summary>
        internal static string qhd {
            get {
                return ResourceManager.GetString("qhd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom resolution.
        /// </summary>
        internal static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string rows_edit_text {
            get {
                return ResourceManager.GetString("rows_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to save file: .
        /// </summary>
        internal static string save_file_error_with_comment {
            get {
                return ResourceManager.GetString("save_file_error_with_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2160p (Ultra HD).
        /// </summary>
        internal static string uhd {
            get {
                return ResourceManager.GetString("uhd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        internal static string victory {
            get {
                return ResourceManager.GetString("victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Level.
        /// </summary>
        internal static string volume {
            get {
                return ResourceManager.GetString("volume", resourceCulture);
            }
        }
    }
}
